config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :users
  post 'store_user', to: 'users#store_user', as: 'store_user'
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    User.create(
      name: session[:name],
      time: params[:time]
    )
    redirect_to root_path
  end

  def store_user
    # so user can stay on same page and reuse session name
    session[:name] = user_params[:name]
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= image_tag "button.png", id: "button" %>

<div>Time: <span id="time"></span></div>

<%= render partial: 'users/new' %>

app/views/home/index.html.haml
%button.btn.btn-default Button

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ButtonKing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body onload="showClock();">

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Button King
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .container
      - if notice
        .alert.alert-info.alert-dismissable{ role: :alert }
          %button.close{ type: :button, aria: { label: "Close" }, data: { dismiss: :alert }}
            %span{ aria: { hidden: "true" }} &times;
          = notice
      - if alert
        .alert.alert-danger{ role: :alert }= alert
      = yield

app/views/users/_new.html.erb
<div class="modal fade" id="signinModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Sign in</h4>
      </div>
      <div class="modal-body">
        <%= form_for @user, remote: true, url: store_user_path, method: "post", class: "form-inline" do |f| %>
          <%= f.label "Hi! What's your name?" %>
          <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="modal-footer">
          <%= f.submit "Play!", class: "btn btn-primary", onclick: "closeModal()" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.haml
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>